### ISSUE TITLE
componentWillReceiveProps transfrom result was wrong

### ISSUE THREAD

**Issue by Binaryify** [vueact/babel-plugin-transform-react-to-vue#5]
I think the `componentWillReceiveProps` transfrom result was wrong
![image](https://user-images.githubusercontent.com/12221718/28742858-c3829144-746d-11e7-9608-1904077edfc0.png)
I think it can be transfrom to this:
```js
 watch: {
    $props: {
      deep: true,
      handler(nextProps={}) {
        //xxx
      }
    }
  }
```

**Comment by nickmessing** [comment]
You are right

**Comment by nickmessing** [comment]
#17 should fix it.
