### ISSUE TITLE
React.Component is not transformed

### ISSUE THREAD

**Issue by armano2** [vueact/babel-plugin-transform-react-to-vue#9]
When i tried to transform https://github.com/ahfarmer/calculator/blob/master/src/component/App.js
its not working React.Component !== Component

see: https://github.com/vueact/babel-plugin-transform-react-to-vue/blob/master/index.js#L350
we should also check if imported Identifier is React and do additional checks in `ClassDeclaration`

**Comment by nickmessing** [comment]
@armano2, I think we can just hardcode `React` check since JSX forces you to use that :smile:

**Comment by armano2** [comment]
I never worked with react, i just was playing around with this tool 🗡

**Comment by egoist** [comment]
Done https://github.com/vueact/babel-plugin-transform-react-to-vue/pull/12
